CREATE OR ALTER VIEW [dbo].[VISTA_ACUDIENTES]
AS
SELECT
    [IDENTIFICACION],
    CONCAT([PRIMERNOMBRE], ' ', [SEGUNDONOMBRE]) AS NOMBRES,
    CONCAT([PRIMERAPELLIDO], ' ', [SEGUNDOAPELLIDO]) AS APELLIDOS,
    [TELEFONO],
    DATEDIFF(YEAR, [FECHANACIMIENTO], GETDATE()) - 
        CASE 
            WHEN MONTH(GETDATE()) < MONTH([FECHANACIMIENTO]) OR 
                 (MONTH(GETDATE()) = MONTH([FECHANACIMIENTO]) AND DAY(GETDATE()) < DAY([FECHANACIMIENTO]))
            THEN 1 
            ELSE 0 
        END AS EDAD,
    [EMAIL],
    [FECHANACIMIENTO],
    [DIRECCION]
FROM
    [JulianHernandoDavid_NotasDB].[dbo].[ACUDIENTES] 
GO

SELECT * FROM [dbo].[VISTA_ACUDIENTES] ORDER BY APELLIDOS;