CREATE OR ALTER VIEW [dbo].[VISTA_ESTUDIANTES]
AS
SELECT
    E.[IDENTIFICACION],
    CONCAT(E.[PRIMERNOMBRE], ' ', E.[SEGUNDONOMBRE]) AS NOMBRES,
    CONCAT(E.[PRIMERAPELLIDO], ' ', E.[SEGUNDOAPELLIDO]) AS APELLIDOS,
    E.[TELEFONO],
    DATEDIFF(YEAR, E.[FECHANACIMIENTO], GETDATE()) - 
        CASE 
            WHEN MONTH(GETDATE()) < MONTH(E.[FECHANACIMIENTO]) OR 
                 (MONTH(GETDATE()) = MONTH(E.[FECHANACIMIENTO]) AND DAY(GETDATE()) < DAY(E.[FECHANACIMIENTO]))
            THEN 1 
            ELSE 0 
        END AS EDAD,
    E.[EMAIL],
    E.[FECHANACIMIENTO],
    E.[DIRECCION],
	CONCAT(G.NOMBRE,'°-',C.[CODIGO]) AS GRUPO
FROM
    [JulianHernandoDavid_NotasDB].[dbo].[ESTUDIANTES] E
	INNER JOIN CURSOS C ON C.IDCURSO =  E.[CURSO]
	INNER JOIN GRADOS G ON G.IDGRADO =  C.[GRADO]
GO

SELECT * FROM [dbo].[VISTA_ESTUDIANTES] ORDER BY APELLIDOS;
