USE [master]
GO

/****** Object:  Database [JulianHernandoDavid_NotasDB]    Script Date: 25/05/2024 23:45:39 ******/
DROP DATABASE [JulianHernandoDavid_NotasDB]
GO

/****** Object:  Database [JulianHernandoDavid_NotasDB]    Script Date: 25/05/2024 23:45:39 ******/
CREATE DATABASE [JulianHernandoDavid_NotasDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HernandoJulianDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\HernandoJulianDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HernandoJulianDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\HernandoJulianDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [JulianHernandoDavid_NotasDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [JulianHernandoDavid_NotasDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [JulianHernandoDavid_NotasDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [JulianHernandoDavid_NotasDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [JulianHernandoDavid_NotasDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [JulianHernandoDavid_NotasDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [JulianHernandoDavid_NotasDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [JulianHernandoDavid_NotasDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [JulianHernandoDavid_NotasDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [JulianHernandoDavid_NotasDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [JulianHernandoDavid_NotasDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [JulianHernandoDavid_NotasDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [JulianHernandoDavid_NotasDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [JulianHernandoDavid_NotasDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [JulianHernandoDavid_NotasDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [JulianHernandoDavid_NotasDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [JulianHernandoDavid_NotasDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [JulianHernandoDavid_NotasDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [JulianHernandoDavid_NotasDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [JulianHernandoDavid_NotasDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [JulianHernandoDavid_NotasDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [JulianHernandoDavid_NotasDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [JulianHernandoDavid_NotasDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [JulianHernandoDavid_NotasDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [JulianHernandoDavid_NotasDB] SET  MULTI_USER 
GO

ALTER DATABASE [JulianHernandoDavid_NotasDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [JulianHernandoDavid_NotasDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [JulianHernandoDavid_NotasDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [JulianHernandoDavid_NotasDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [JulianHernandoDavid_NotasDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [JulianHernandoDavid_NotasDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [JulianHernandoDavid_NotasDB] SET QUERY_STORE = ON
GO

ALTER DATABASE [JulianHernandoDavid_NotasDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [JulianHernandoDavid_NotasDB] SET  READ_WRITE 
GO


